[model]
seed = 7
keep_days = 1
percent = 1
interval = 288
type = flow
num_nodes = 15
num_features = 3
num_heads = 4,4,4,4,4
partial = 4
channels = 3,32,32,32,32,32
depth = 5
t_history = 12
t_pred = 12
epochs = 120
lr = 1e-2
weight_decay = 0.0001
batch_size = 128
dropout = 0.2
train = True
test = True
val = True